[features]
seeds = false
skip-lint = false

[programs.localnet]
bunachain = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"  # auto-filled by Anchor locally

[programs.devnet]
bunachain = "REPLACE_WITH_DEPLOYED_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
